language: python

python:
  - "2.7"

sudo: false
cache: pip

addons:
  postgresql: "9.3" # minimal postgresql version for the base_import_security_group module
                    # more info: https://github.com/OCA/maintainer-quality-tools/issues/432
  apt:
    packages:
      - python-lxml  # because pip installation is slow

env:
  global:
  - VERSION="10.0" TESTS="0" LINT_CHECK="0"

  matrix:
  - LINT_CHECK="1"
  - TESTS="1" ODOO_REPO="odoo/odoo"
  - TESTS="1" ODOO_REPO="OCA/OCB"

virtualenv:
  system_site_packages: true

install:
  - git clone --depth=1 https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - git clone --depth=1 https://github.com/OCA/sale-workflow.git ${HOME}/sale-workflow
  - export PATH=${HOME}/sale-workflow/travis:${PATH}
  - pip install unidecode
  - travis_install_nightly 

script:
  - travis_run_tests

after_success:
  - travis_after_tests_success
 
